
-- 관리자 > 시스템 > 이용내역 메뉴 추가
INSERT INTO `eroumcare`.`MNG_MENU` 
(`UP_MENU_NO`, `MENU_NM`, `MENU_URL`, `MENU_TY`, `LEVEL_NO`, `SORT_NO`, `USE_YN`) 
VALUES ('4', '묶음배송 그룹관리', '/_mng/sysmng/entrps/dlvygrp/list', '4', '1', '5', 'Y');

-- 입점업체별 묶음배송
CREATE TABLE `ENTRPS_DLVYGRP` (
	`ENTRPS_DLVYGRP_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '업체별 묶음배송 번호',
	`ENTRPS_NO` INT(11) NOT NULL COMMENT '업체_번호',
	`ENTRPS_DLVYGRP_NM` VARCHAR(12) NOT NULL COMMENT '업체별 묶음배송 명' COLLATE 'utf8mb4_unicode_ci',
	`DLVY_ADIT_AMT` INT(11) NOT NULL COMMENT '배송 추가 금액',
	`USE_YN` CHAR(1) NOT NULL COMMENT '사용여부' COLLATE 'utf8mb4_unicode_ci',
	`REG_UNIQUE_ID` VARCHAR(50) NULL DEFAULT NULL COMMENT '등록_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
	`REG_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록_아이디' COLLATE 'utf8mb4_unicode_ci',
	`RGTR` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자' COLLATE 'utf8mb4_unicode_ci',
	`MDFCN_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '수정_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시',
	`MDFCN_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MDFR` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`ENTRPS_DLVYGRP_NO`),
	INDEX `ENTRPS_NO` (`ENTRPS_NO`)
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
