
-- 관리자 상세보기 로그 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`MNGR_DETAIL_LOG` (
    `LOG_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '관리자_유니크_ID',
    `MNGR_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '관리자_ID',
    `MNGR_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '관리자명',
    `URL` VARCHAR(1024) NULL DEFAULT NULL COMMENT '접근 URL',
    `DMND_IP` VARCHAR(15) NULL DEFAULT NULL COMMENT '접근 IP',
    `USE_HIST` VARCHAR(1024) NULL DEFAULT NULL COMMENT '이용내역',
    `RESN` VARCHAR(1024) NULL DEFAULT NULL COMMENT '사유',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    PRIMARY KEY (`LOG_NO`)
)
COMMENT='관리자 상세보기 로그 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;


-- 관리자 엑셀다운로드 로그 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`MNGR_EXCEL_LOG` (
    `LOG_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '관리자_유니크_ID',
    `MNGR_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '관리자_ID',
    `MNGR_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '관리자명',
    `URL` VARCHAR(1024) NULL DEFAULT NULL COMMENT '접근 URL',
    `DMND_IP` VARCHAR(15) NULL DEFAULT NULL COMMENT '접근 IP',
    `USE_HIST` VARCHAR(1024) NULL DEFAULT NULL COMMENT '이용내역',
    `RESN` VARCHAR(1024) NULL DEFAULT NULL COMMENT '사유',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    PRIMARY KEY (`LOG_NO`)
)
COMMENT='관리자 엑셀다운로드 로그 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;


-- 관리자 > 시스템 > 이용내역 메뉴 추가
INSERT INTO `eroumcare`.`MNG_MENU` 
(`UP_MENU_NO`, `MENU_NM`, `MENU_URL`, `MENU_TY`, `LEVEL_NO`, `SORT_NO`, `USE_YN`) 
VALUES ('9', '이용내역', '/_mng/sysmng/log/list', '4', '1', '10', 'Y');