ALTER TABLE MBR_MLG ADD EXTINCT_MAIL_YN CHAR(1) NULL DEFAULT NULL COMMENT '만료 안내 이메일 발송 여부';
ALTER TABLE MBR_MLG ADD EXTINCT_YN CHAR(1) NULL DEFAULT NULL COMMENT '만료 처리 여부';

ALTER TABLE MBR ADD HUMAN_MAIL_YN CHAR(1) NULL DEFAULT NULL COMMENT '휴면계정대상 이메일 발송 여부';