CREATE TABLE IF NOT EXISTS `eroumcare`.`MBR_RECIPIENTS` (
    `RECIPIENTS_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `MBR_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '회원_유일_아이디',
    `RECIPIENTS_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '수급자 또는 예비수급자명',
    `RECIPIENTS_YN` CHAR(1) NULL DEFAULT NULL COMMENT '수급자 여부',
    `RCPER_RCOGN_NO` VARCHAR(100) NULL DEFAULT NULL COMMENT '요양 인정 번호',
    `TEL` VARCHAR(15) NULL DEFAULT NULL COMMENT '연락처',
    `SIDO` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '시도',
    `SIGUGUN` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '시군구',
    `DONG` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '동읍면',
    `GENDER` CHAR(1) NULL DEFAULT NULL COMMENT '성별',
    `BRDT` CHAR(8) NULL DEFAULT NULL COMMENT '생년월일',
    `RELATION_CD` CHAR(3) NULL DEFAULT NULL COMMENT '수급자와의 관계 코드',
    `MAIN_YN` CHAR(1) NULL DEFAULT NULL COMMENT '대표 수급자 여부',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    `MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시',
    PRIMARY KEY (`RECIPIENTS_NO`)
)
COMMENT='회원 수급자 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS `eroumcare`.`MBR_AGREEMENT` (
    `AGREEMENT_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `MBR_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '회원_유일_아이디',
    `TERMS_YN` CHAR(1) NULL DEFAULT NULL COMMENT '이용약관 동의 여부',
    `TERMS_DT` DATETIME NULL DEFAULT NULL COMMENT '이용약관 동의 여부 선택시간',
    `PRIVACY_YN` CHAR(1) NULL DEFAULT NULL COMMENT '개인정보 처리방침 동의 여부',
    `PRIVACY_DT` DATETIME NULL DEFAULT NULL COMMENT '개인정보 처리방침 동의 여부 선택시간',
    `PROVISION_YN` CHAR(1) NULL DEFAULT NULL COMMENT '개인정보 제공 동의 여부',
    `PROVISION_DT` DATETIME NULL DEFAULT NULL COMMENT '개인정보 제공 동의 선택시간',
    `THIRD_PARTIES_YN` CHAR(1) NULL DEFAULT NULL COMMENT '개인정보 제3자 제공 동의 여부',
    `THIRD_PARTIES_DT` DATETIME NULL DEFAULT NULL COMMENT '개인정보 제3자 제공 동의 여부 선택시간',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    `MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시',
    PRIMARY KEY (`AGREEMENT_NO`)
)
COMMENT='회원 동의 로그 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;


ALTER TABLE MBR ADD SMS_RCPTN_DT DATETIME NULL DEFAULT NULL COMMENT '문자메시지 수신 여부 선택시간' AFTER SMS_RCPTN_YN;
ALTER TABLE MBR ADD EML_RCPTN_DT DATETIME NULL DEFAULT NULL COMMENT '이메일 수신 여부 선택시간' AFTER EML_RCPTN_YN;
ALTER TABLE MBR ADD TEL_RECPTN_DT DATETIME NULL DEFAULT NULL COMMENT '전화 수신 여부 선택시간' AFTER TEL_RECPTN_YN;
ALTER TABLE MBR ADD SNS_REGIST_DT DATETIME NULL DEFAULT NULL COMMENT '간편 로그인 최초가입일';


ALTER TABLE MBR_TEST ADD RECIPIENTS_NO INT(11) NULL DEFAULT NULL COMMENT '등록된 수급자 FK 번호' AFTER UNIQUE_ID;


ALTER TABLE MBR_CONSLT MODIFY ZIP VARCHAR(255);
ALTER TABLE MBR_CONSLT ADD RECIPIENTS_NO INT(11) NULL DEFAULT NULL COMMENT '상담 수급자 번호';
ALTER TABLE MBR_CONSLT ADD RELATION_CD CHAR(3) NULL DEFAULT NULL COMMENT '수급자와의 관계 코드';
ALTER TABLE MBR_CONSLT ADD RCPER_RCOGN_NO VARCHAR(100) NULL DEFAULT NULL COMMENT '장기요양인정번호';
ALTER TABLE MBR_CONSLT ADD PREV_PATH VARCHAR(32) NULL DEFAULT NULL COMMENT '상담 신청 경로';