-- 수급자의 복지용구 선택 정보 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`MBR_RECIPIENTS_GDS` (
    `RECIPIENTS_GDS_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `RECIPIENTS_NO` INT(11) NULL DEFAULT NULL COMMENT '수급자_번호',
    `CONSLT_GDS_TY` CHAR(3) NULL DEFAULT NULL COMMENT '카테고리 또는 상품 타입',
    `CTGRY_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '선택_카테고리명',
    `CARE_CTGRY_CD` VARCHAR(32) NULL DEFAULT NULL COMMENT '케어_카테고리_코드',
    `GDS_NO` INT(11) NULL DEFAULT NULL COMMENT '선택_상품_넘버',
    `MBR_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '회원_유니크_ID',
    `MBR_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '회원ID',
    `MBR_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '회원명',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    PRIMARY KEY (`RECIPIENTS_GDS_NO`)
)
COMMENT='수급자의 복지용구 선택 정보'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;

-- 상담의 복지용구 선택 정보 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`MBR_CONSLT_GDS` (
    `CONSLT_GDS_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `CONSLT_NO` INT(11) NULL DEFAULT NULL COMMENT '상담_번호',
    `CONSLT_GDS_TY` CHAR(3) NULL DEFAULT NULL COMMENT '카테고리 또는 상품 타입',
    `CTGRY_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '선택_카테고리명',
    `CARE_CTGRY_CD` VARCHAR(32) NULL DEFAULT NULL COMMENT '케어_카테고리_코드',
    `GDS_NO` INT(11) NULL DEFAULT NULL COMMENT '선택_상품_넘버',
    `MBR_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '회원_유니크_ID',
    `MBR_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '회원ID',
    `MBR_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '회원명',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    PRIMARY KEY (`CONSLT_GDS_NO`)
)
COMMENT='상담의 복지용구 선택 정보'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;