
-- 관리자 > 시스템 > 이용내역 메뉴 추가
INSERT INTO `eroumcare`.`MNG_MENU` 
(`UP_MENU_NO`, `MENU_NM`, `MENU_URL`, `MENU_TY`, `LEVEL_NO`, `SORT_NO`, `USE_YN`) 
VALUES ('4', '묶음배송 그룹관리', '/_mng/sysmng/entrps/dlvygrp/list', '4', '1', '5', 'Y');

/* 입점업체가 없는 경우 강제로 세팅
update gds
SET entrps_no = 1
WHERE entrps_no IN (0, NULL)
*/

ALTER TABLE GDS ADD COLUMN IF NOT EXISTS `ENTRPS_DLVYGRP_NO` INT NULL DEFAULT NULL COMMENT '묶음배송번호'
;

ALTER TABLE CART ADD COLUMN IF NOT EXISTS `VIEW_TN` CHAR(1) NULL  DEFAULT 'Y' COMMENT '사용자 보기 여부(바로구매이면 N으로)'
;

ALTER TABLE ORDR_DTL ADD COLUMN IF NOT EXISTS `GDS_OPTN_NO` INT NULL DEFAULT NULL COMMENT '상품 옵션 번호'
;
ALTER TABLE ORDR_DTL ADD COLUMN IF NOT EXISTS `DLVY_GROUP_YN` INT NULL DEFAULT NULL COMMENT '상품 옵션 번호'
;
ALTER TABLE ORDR_DTL ADD COLUMN IF NOT EXISTS `ENTRPS_DLVYGRP_NO` INT NULL DEFAULT NULL COMMENT '묶음배송번호'
;

ALTER TABLE CART ADD COLUMN IF NOT EXISTS `MDFCN_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '수정_유일_아이디';
ALTER TABLE CART ADD COLUMN IF NOT EXISTS `MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시';
ALTER TABLE CART ADD COLUMN IF NOT EXISTS `MDFCN_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정_아이디';
ALTER TABLE CART ADD COLUMN IF NOT EXISTS `MDFR` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자';

ALTER TABLE ENTRPS ADD COLUMN IF NOT EXISTS `ENTRPS_STORE_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '입점업체 스토어명'
/*
UPDATE entrps
SET ENTRPS_STORE_NM = ENTRPS_NM
WHERE ENTRPS_ALIAS IS null
*/

CREATE TABLE `ENTRPS_DLVYGRP` (
	`ENTRPS_DLVYGRP_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '업체별 묶음배송 번호',
	`ENTRPS_NO` INT(11) NOT NULL COMMENT '업체_번호',
	`ENTRPS_DLVYGRP_NM` VARCHAR(12) NOT NULL COMMENT '업체별 묶음배송 명' COLLATE 'utf8mb4_unicode_ci',
	`DLVY_ADIT_AMT` INT(11) NOT NULL COMMENT '배송 추가 금액',
	`DLVY_CALC_TY` VARCHAR(50) NULL DEFAULT NULL COMMENT '배송비 계산 방식' COLLATE 'utf8mb4_unicode_ci',
	`USE_YN` CHAR(1) NOT NULL COMMENT '사용여부' COLLATE 'utf8mb4_unicode_ci',
	`DEL_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부' COLLATE 'utf8mb4_unicode_ci',
	`DEL_AT_GDS` TEXT NULL DEFAULT NULL COMMENT '삭제시 상품의 리스트' COLLATE 'utf8mb4_unicode_ci',
	`REG_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '등록_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
	`REG_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록_아이디' COLLATE 'utf8mb4_unicode_ci',
	`RGTR` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자' COLLATE 'utf8mb4_unicode_ci',
	`MDFCN_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '수정_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시',
	`MDFCN_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MDFR` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자' COLLATE 'utf8mb4_unicode_ci',
	`DEL_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`DEL_DT` DATETIME NULL DEFAULT NULL,
	`DEL_ID` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`ENTRPS_DLVYGRP_NO`) USING BTREE,
	INDEX `ENTRPS_NO` (`ENTRPS_NO`) USING BTREE
)
COMMENT='입점업체별 묶음배송'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=10
;
