

/*
CREATE TABLE `Z_BAK_MBR_231114` (
	`UNIQUE_ID` VARCHAR(12) NOT NULL COMMENT '유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MBR_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '회원_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MBR_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '회원_명' COLLATE 'utf8mb4_unicode_ci',
	`PSWD` VARCHAR(255) NULL DEFAULT NULL COMMENT '비밀번호' COLLATE 'utf8mb4_unicode_ci',
	`GENDER` CHAR(1) NULL DEFAULT NULL COMMENT '성별' COLLATE 'utf8mb4_unicode_ci',
	`BRDT` DATE NULL DEFAULT NULL COMMENT '생년월일',
	`TELNO` VARCHAR(15) NULL DEFAULT NULL COMMENT '전화번호' COLLATE 'utf8mb4_unicode_ci',
	`MBL_TELNO` VARCHAR(15) NULL DEFAULT NULL COMMENT '휴대전화번호' COLLATE 'utf8mb4_unicode_ci',
	`EML` VARCHAR(255) NULL DEFAULT NULL COMMENT '이메일' COLLATE 'utf8mb4_unicode_ci',
	`ZIP` VARCHAR(5) NULL DEFAULT NULL COMMENT '우편번호' COLLATE 'utf8mb4_unicode_ci',
	`ADDR` VARCHAR(255) NULL DEFAULT NULL COMMENT '주소' COLLATE 'utf8mb4_unicode_ci',
	`DADDR` VARCHAR(255) NULL DEFAULT NULL COMMENT '상세주소' COLLATE 'utf8mb4_unicode_ci',
	`DI_KEY` VARCHAR(255) NULL DEFAULT NULL COMMENT '본인_인증_ 키' COLLATE 'utf8mb4_unicode_ci',
	`NAVER_APP_ID` VARCHAR(255) NULL DEFAULT NULL COMMENT '네이버_앱_아이디' COLLATE 'utf8mb4_unicode_ci',
	`KAKAO_APP_ID` VARCHAR(255) NULL DEFAULT NULL COMMENT '카카오_앱_아이디' COLLATE 'utf8mb4_unicode_ci',
	`RECIPTER_YN` CHAR(1) NULL DEFAULT NULL COMMENT '수급자_여부' COLLATE 'utf8mb4_unicode_ci',
	`BASS_STLM_TY` VARCHAR(10) NULL DEFAULT NULL COMMENT '기본_결제_유형' COLLATE 'utf8mb4_unicode_ci',
	`POINT_ACMTL` INT(11) NULL DEFAULT NULL COMMENT '포인트_누계',
	`MLG_ACMTL` INT(11) NULL DEFAULT NULL COMMENT '마일리지_누계',
	`MBER_STTUS` VARCHAR(10) NULL DEFAULT NULL COMMENT '회원_상태' COLLATE 'utf8mb4_unicode_ci',
	`MBER_GRADE` VARCHAR(10) NULL DEFAULT NULL COMMENT '회원_등급' COLLATE 'utf8mb4_unicode_ci',
	`RCMDTN_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '추천_아이디' COLLATE 'utf8mb4_unicode_ci',
	`RCMDTN_MBRS_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '추천_멤버스_아이디' COLLATE 'utf8mb4_unicode_ci',
	`PRVC_VLD_PD` VARCHAR(10) NULL DEFAULT NULL COMMENT '개인정보_유효_기간' COLLATE 'utf8mb4_unicode_ci',
	`SMS_RCPTN_YN` CHAR(1) NULL DEFAULT NULL COMMENT '문자메시지_수신_여부' COLLATE 'utf8mb4_unicode_ci',
	`SMS_RCPTN_DT` DATETIME NULL DEFAULT NULL COMMENT '문자메시지 수신 여부 선택시간',
	`EML_RCPTN_YN` CHAR(1) NULL DEFAULT NULL COMMENT '이메일_수신_여부' COLLATE 'utf8mb4_unicode_ci',
	`EML_RCPTN_DT` DATETIME NULL DEFAULT NULL COMMENT '이메일 수신 여부 선택시간',
	`TEL_RECPTN_YN` CHAR(1) NULL DEFAULT NULL COMMENT '전화_수신_여부' COLLATE 'utf8mb4_unicode_ci',
	`TEL_RECPTN_DT` DATETIME NULL DEFAULT NULL COMMENT '전화 수신 여부 선택시간',
	`EVENT_RECPTN_YN` CHAR(1) NULL DEFAULT NULL COMMENT '이벤트_수신_여부' COLLATE 'utf8mb4_unicode_ci',
	`PROFL_IMG` VARCHAR(255) NULL DEFAULT NULL COMMENT '프로필_이미지' COLLATE 'utf8mb4_unicode_ci',
	`TRMS_AGRE_DT` DATETIME NULL DEFAULT NULL COMMENT '약관_동의_일시',
	`ITRST_FIELD` VARCHAR(100) NULL DEFAULT NULL COMMENT '관심_분야' COLLATE 'utf8mb4_unicode_ci',
	`JOIN_COURS` VARCHAR(10) NULL DEFAULT NULL COMMENT '가입_경로' COLLATE 'utf8mb4_unicode_ci',
	`JOIN_TY` CHAR(1) NULL DEFAULT NULL COMMENT '가입_구분' COLLATE 'utf8mb4_unicode_ci',
	`JOIN_DT` DATETIME NULL DEFAULT NULL COMMENT '가입_일시',
	`LGN_FAILR_CNT` INT(11) NULL DEFAULT NULL COMMENT '로그인_실패_수',
	`RECENT_CNTN_DT` DATETIME NULL DEFAULT NULL COMMENT '최근_접속_일시',
	`TMPR_PSWD_YN` CHAR(1) NULL DEFAULT NULL COMMENT '임시_비밀번호_여부' COLLATE 'utf8mb4_unicode_ci',
	`PSWD_CHG_DT` DATETIME NULL DEFAULT NULL COMMENT '비밀번호_변경_일시',
	`MDFCN_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '수정_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시',
	`MDFCN_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MDFR` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자' COLLATE 'utf8mb4_unicode_ci',
	`WHDWL_YN` CHAR(1) NULL DEFAULT NULL COMMENT '탈퇴_여부' COLLATE 'utf8mb4_unicode_ci',
	`WHDWL_DT` DATETIME NULL DEFAULT NULL COMMENT '탈퇴_일시',
	`WHDWL_RESN` VARCHAR(255) NULL DEFAULT NULL COMMENT '탈퇴_사유' COLLATE 'utf8mb4_unicode_ci',
	`WHDWL_TY` VARCHAR(10) NULL DEFAULT NULL COMMENT '탈퇴_유형' COLLATE 'utf8mb4_unicode_ci',
	`WHDWL_ETC` VARCHAR(255) NULL DEFAULT NULL COMMENT '탈퇴_기타' COLLATE 'utf8mb4_unicode_ci',
	`SNS_REGIST_DT` DATETIME NULL DEFAULT NULL COMMENT '간편 로그인 최초가입일',
	PRIMARY KEY (`UNIQUE_ID`) USING BTREE
)
COMMENT='회원'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
*/

/*
"UNIQUE_ID"	"MBR_ID"	"MBR_NM"
"MBR_00000003"	"naoko97"	"전명희"
"MBR_00000012"	"behush"	"이지민"
"MBR_00000013"	"kumakuma"	"이지민"
"MBR_00000014"	"sjbaek01"	"백승정"
"MBR_00000019"	"naoko14"	"전명희"
"MBR_00000020"	"naoko123"	"전명희"
"MBR_00000022"	"xinren99"	"박진호"
"MBR_00000035"	"ssiboro"	"조용호"
"MBR_00000038"	"icube2023"	"김정래"
"MBR_00000045"	"naoko78"	"전명희"
"MBR_00000076"	"jiaUFDVU36DHckGLl6r69oQhSwn1QRm9qgbi3UycdX0@N"	"백승정"
"MBR_00000078"	"2905314485@K"	"전명희"
"MBR_00000102"	"7nbf2oQj4k0PEdHXmErbXV5raiUggnZVKWFVrTcor1k@N"	"정현욱"
"MBR_00000125"	"bgV1-CGx9fc1o0nWjVFPqRwMsJOEgJZND3os55zpAr4@N"	"박서원"
"MBR_00000134"	"8168248231@N"	"이효진"
"MBR_00000182"	"5374908622@N"	"이효진"
*/