/*
DELETE 
FROM ORDR_CHG_HIST
WHERE ordr_no IN (SELECT ordr_no
						FROM ORDR
						WHERE ordr_cd NOT IN ('O31110165133905', 'O31110145947595', 'O31101171104930') AND ordr_dt < '2023-11-14'
					)
;

DELETE 
FROM ORDR_DTL
WHERE ordr_no IN (SELECT ordr_no
						FROM ORDR
						WHERE ordr_cd NOT IN ('O31110165133905', 'O31110145947595', 'O31101171104930') AND ordr_dt < '2023-11-14'
					)
;

DELETE 
FROM ORDR
WHERE ordr_cd NOT IN ('O31110165133905', 'O31110145947595', 'O31101171104930')
	AND ordr_dt < '2023-11-14'
;
*/

/*
CREATE TABLE `Z_BAK_ORDR_231114` (
	`ORDR_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '주문_번호',
	`ORDR_CD` VARCHAR(100) NOT NULL COMMENT '주문_코드' COLLATE 'utf8mb4_unicode_ci',
	`UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`ORDR_TY` VARCHAR(10) NULL DEFAULT NULL COMMENT '주문_유형' COLLATE 'utf8mb4_unicode_ci',
	`ORDR_DT` DATETIME NULL DEFAULT NULL COMMENT '주문_일시',
	`ORDRR_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '주문자_아이디' COLLATE 'utf8mb4_unicode_ci',
	`ORDRR_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '주문자_명' COLLATE 'utf8mb4_unicode_ci',
	`ORDRR_EML` VARCHAR(255) NULL DEFAULT NULL COMMENT '주문자_이메일' COLLATE 'utf8mb4_unicode_ci',
	`ORDRR_TELNO` VARCHAR(15) NULL DEFAULT NULL COMMENT '주문자_전화번호' COLLATE 'utf8mb4_unicode_ci',
	`ORDRR_MBL_TELNO` VARCHAR(15) NULL DEFAULT NULL COMMENT '주문자_휴대전화번호' COLLATE 'utf8mb4_unicode_ci',
	`ORDRR_ZIP` VARCHAR(5) NULL DEFAULT NULL COMMENT '주문자_우편번호' COLLATE 'utf8mb4_unicode_ci',
	`ORDRR_ADDR` VARCHAR(255) NULL DEFAULT NULL COMMENT '주문자_주소' COLLATE 'utf8mb4_unicode_ci',
	`ORDRR_DADDR` VARCHAR(255) NULL DEFAULT NULL COMMENT '주문자_상세주소' COLLATE 'utf8mb4_unicode_ci',
	`ORDRR_MEMO` TEXT NULL DEFAULT NULL COMMENT '주문자_메모' COLLATE 'utf8mb4_unicode_ci',
	`RECPTR_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '수령인_명' COLLATE 'utf8mb4_unicode_ci',
	`RECPTR_TELNO` VARCHAR(15) NULL DEFAULT NULL COMMENT '수령인_전화번호' COLLATE 'utf8mb4_unicode_ci',
	`RECPTR_MBL_TELNO` VARCHAR(15) NULL DEFAULT NULL COMMENT '수령인_휴대전화번호' COLLATE 'utf8mb4_unicode_ci',
	`RECPTR_ZIP` VARCHAR(5) NULL DEFAULT NULL COMMENT '수령인_우편번호' COLLATE 'utf8mb4_unicode_ci',
	`RECPTR_ADDR` VARCHAR(255) NULL DEFAULT NULL COMMENT '수령인_주소' COLLATE 'utf8mb4_unicode_ci',
	`RECPTR_DADDR` VARCHAR(255) NULL DEFAULT NULL COMMENT '수령인_상세주소' COLLATE 'utf8mb4_unicode_ci',
	`USE_MLG` INT(11) NULL DEFAULT NULL COMMENT '사용_마일리지',
	`USE_POINT` INT(11) NULL DEFAULT NULL COMMENT '사용_포인트',
	`STLM_DEVICE` VARCHAR(100) NULL DEFAULT NULL COMMENT '결제_디바이스' COLLATE 'utf8mb4_unicode_ci',
	`STLM_TY` VARCHAR(20) NULL DEFAULT NULL COMMENT '결제_유형' COLLATE 'utf8mb4_unicode_ci',
	`STLM_AMT` INT(11) NULL DEFAULT NULL COMMENT '결제_금액',
	`STLM_YN` CHAR(1) NULL DEFAULT NULL COMMENT '결제_여부' COLLATE 'utf8mb4_unicode_ci',
	`STLM_DT` DATETIME NULL DEFAULT NULL COMMENT '결제_일시',
	`DELNG_NO` VARCHAR(100) NULL DEFAULT NULL COMMENT '거래번호' COLLATE 'utf8mb4_unicode_ci',
	`BILLING_YN` CHAR(1) NULL DEFAULT NULL COMMENT '빌링_여부' COLLATE 'utf8mb4_unicode_ci',
	`BILLING_KEY` VARCHAR(100) NULL DEFAULT NULL COMMENT '빌링_키' COLLATE 'utf8mb4_unicode_ci',
	`BILLING_DAY` VARCHAR(2) NULL DEFAULT NULL COMMENT '빌링_일자' COLLATE 'utf8mb4_unicode_ci',
	`CARD_CO_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '카드_회사명' COLLATE 'utf8mb4_unicode_ci',
	`CARD_NO` VARCHAR(100) NULL DEFAULT NULL COMMENT '카드_번호' COLLATE 'utf8mb4_unicode_ci',
	`CARD_APRVNO` VARCHAR(100) NULL DEFAULT NULL COMMENT '카드_승인번호' COLLATE 'utf8mb4_unicode_ci',
	`CARD_PRTC_YN` CHAR(1) NULL DEFAULT NULL COMMENT '부분취소_가능여부' COLLATE 'utf8mb4_unicode_ci',
	`VR_ACTNO` VARCHAR(100) NULL DEFAULT NULL COMMENT '가상_계좌번호' COLLATE 'utf8mb4_unicode_ci',
	`DPST_BANK_CD` VARCHAR(100) NULL DEFAULT NULL COMMENT '입금_은행_코드' COLLATE 'utf8mb4_unicode_ci',
	`DPST_BANK_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '입금_은행_명' COLLATE 'utf8mb4_unicode_ci',
	`DPSTR` VARCHAR(100) NULL DEFAULT NULL COMMENT '입금_예금주' COLLATE 'utf8mb4_unicode_ci',
	`PYR_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '입금자_명' COLLATE 'utf8mb4_unicode_ci',
	`DPST_TERM_DT` DATETIME NULL DEFAULT NULL COMMENT '입금_기한_일시',
	`CASHRCIPT_YN` CHAR(1) NULL DEFAULT NULL COMMENT '현금영수증_여부' COLLATE 'utf8mb4_unicode_ci',
	`CASHRCIPT_NO` VARCHAR(100) NULL DEFAULT NULL COMMENT '현금영수증_번호' COLLATE 'utf8mb4_unicode_ci',
	`SEND_STTUS` CHAR(1) NULL DEFAULT NULL COMMENT '주문정보_송신상태' COLLATE 'utf8mb4_unicode_ci',
	`STLM_STTUS` CHAR(1) NULL DEFAULT NULL COMMENT '결제정보_송신상태' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`ORDR_NO`, `ORDR_CD`) USING BTREE
)
COMMENT='주문'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=56
;


CREATE TABLE `Z_BAK_ORDR_CHG_HIST_231114` (
	`CHG_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '변경_번호',
	`ORDR_NO` INT(11) NULL DEFAULT NULL COMMENT '주문_번호',
	`ORDR_DTL_NO` INT(11) NULL DEFAULT NULL COMMENT '주문_상세_번호',
	`CHG_STTS` VARCHAR(10) NULL DEFAULT NULL COMMENT '변경_상태' COLLATE 'utf8mb4_unicode_ci',
	`RESN_TY` VARCHAR(10) NULL DEFAULT NULL COMMENT '사유_타입' COLLATE 'utf8mb4_unicode_ci',
	`RESN` TEXT NULL DEFAULT NULL COMMENT '사유' COLLATE 'utf8mb4_unicode_ci',
	`REG_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '등록_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
	`REG_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록_아이디' COLLATE 'utf8mb4_unicode_ci',
	`RGTR` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`CHG_NO`) USING BTREE
)
COMMENT='주문-변경내역'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=498
;


CREATE TABLE `Z_BAK_ORDR_DTL_231114` (
	`ORDR_DTL_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '주문_상세_번호',
	`ORDR_NO` INT(11) NOT NULL COMMENT '주문_번호',
	`ORDR_DTL_CD` VARCHAR(100) NOT NULL COMMENT '주문_상세_코드' COLLATE 'utf8mb4_unicode_ci',
	`ORDR_CD` VARCHAR(100) NOT NULL COMMENT '주문_코드' COLLATE 'utf8mb4_unicode_ci',
	`GDS_NO` INT(11) NULL DEFAULT NULL COMMENT '상품_번호',
	`GDS_CD` VARCHAR(20) NULL DEFAULT NULL COMMENT '상품_코드' COLLATE 'utf8mb4_unicode_ci',
	`BNEF_CD` VARCHAR(20) NULL DEFAULT NULL COMMENT '급여_코드' COLLATE 'utf8mb4_unicode_ci',
	`GDS_NM` VARCHAR(255) NULL DEFAULT NULL COMMENT '상품_명' COLLATE 'utf8mb4_unicode_ci',
	`GDS_PC` INT(11) NULL DEFAULT NULL COMMENT '상품_가격',
	`GDS_SUP_PC` VARCHAR(20) NULL DEFAULT NULL COMMENT '공급가' COLLATE 'utf8mb4_unicode_ci',
	`ENTRPS_NO` INT(11) NULL DEFAULT NULL COMMENT '입점업체 NO',
	`ENTRPS_NM` VARCHAR(255) NULL DEFAULT NULL COMMENT '입점업체명' COLLATE 'utf8mb4_unicode_ci',
	`GDS_ITEM_CD` VARCHAR(20) NULL DEFAULT NULL COMMENT '상품 품목코드' COLLATE 'utf8mb4_unicode_ci',
	`OPTN_ITEM_CD` VARCHAR(20) NULL DEFAULT NULL COMMENT '상품 옵션 품목 코드' COLLATE 'utf8mb4_unicode_ci',
	`ORDR_PC` INT(11) NULL DEFAULT NULL COMMENT '주문_가격',
	`ORDR_OPTN_TY` VARCHAR(10) NULL DEFAULT NULL COMMENT '옵션_유형' COLLATE 'utf8mb4_unicode_ci',
	`ORDR_OPTN` VARCHAR(255) NULL DEFAULT NULL COMMENT '주문_옵션' COLLATE 'utf8mb4_unicode_ci',
	`ORDR_OPTN_PC` INT(11) NULL DEFAULT NULL COMMENT '주문_옵션_가격',
	`ORDR_QY` INT(11) NULL DEFAULT NULL COMMENT '주문_수량',
	`ACCML_MLG` INT(11) NULL DEFAULT NULL COMMENT '적립_마일리지',
	`COUPON_NO` INT(11) NULL DEFAULT NULL COMMENT '쿠폰_번호',
	`COUPON_CD` VARCHAR(100) NULL DEFAULT NULL COMMENT '쿠폰_코드' COLLATE 'utf8mb4_unicode_ci',
	`COUPON_AMT` INT(11) NULL DEFAULT NULL COMMENT '쿠폰_금액',
	`REFUND_APRVNO` VARCHAR(255) NULL DEFAULT NULL COMMENT '승인번호' COLLATE 'utf8mb4_unicode_ci',
	`RECIPTER_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '수급자_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`BPLC_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '사업장_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`STTS_TY` VARCHAR(10) NULL DEFAULT NULL COMMENT '상태_유형' COLLATE 'utf8mb4_unicode_ci',
	`SNDNG_DT` DATETIME NULL DEFAULT NULL COMMENT '발송_일시',
	`DLVY_TY` VARCHAR(10) NULL DEFAULT NULL COMMENT '배송_유형' COLLATE 'utf8mb4_unicode_ci',
	`DLVY_HOPE_YMD` VARCHAR(10) NULL DEFAULT NULL COMMENT '배송_희망_일자' COLLATE 'utf8mb4_unicode_ci',
	`DLVY_STLM_TY` VARCHAR(10) NULL DEFAULT NULL COMMENT '배송_결제_유형' COLLATE 'utf8mb4_unicode_ci',
	`DLVY_BASS_AMT` INT(11) NULL DEFAULT NULL COMMENT '배송_금액',
	`DLVY_ADIT_AMT` INT(11) NULL DEFAULT NULL COMMENT '배송_추가_금액',
	`DLVY_STTS` CHAR(1) NULL DEFAULT NULL COMMENT '배송_상태' COLLATE 'utf8mb4_unicode_ci',
	`DLVY_CO_NO` INT(11) NULL DEFAULT NULL COMMENT '배송_회사_번호',
	`DLVY_CO_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '배송_회사' COLLATE 'utf8mb4_unicode_ci',
	`DLVY_DT` DATETIME NULL DEFAULT NULL COMMENT '배송_일시',
	`DLVY_INVC_NO` VARCHAR(100) NULL DEFAULT NULL COMMENT '배송_송장_번호' COLLATE 'utf8mb4_unicode_ci',
	`RFND_YN` CHAR(1) NULL DEFAULT NULL COMMENT '환불_여부' COLLATE 'utf8mb4_unicode_ci',
	`RFND_BANK` VARCHAR(100) NULL DEFAULT NULL COMMENT '환불_은행' COLLATE 'utf8mb4_unicode_ci',
	`RFND_ACTNO` VARCHAR(100) NULL DEFAULT NULL COMMENT '환불_계좌' COLLATE 'utf8mb4_unicode_ci',
	`RFND_AMT` INT(11) NULL DEFAULT NULL COMMENT '환불_금액',
	`RFND_DT` DATETIME NULL DEFAULT NULL COMMENT '환불_일시',
	`RFND_DPSTR` VARCHAR(100) NULL DEFAULT NULL COMMENT '환불_예금주' COLLATE 'utf8mb4_unicode_ci',
	`REG_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '등록_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
	`REG_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록_아이디' COLLATE 'utf8mb4_unicode_ci',
	`RGTR` VARCHAR(100) NULL DEFAULT NULL COMMENT '등록자' COLLATE 'utf8mb4_unicode_ci',
	`MDFCN_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '수정_유일_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시',
	`MDFCN_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정_아이디' COLLATE 'utf8mb4_unicode_ci',
	`MDFR` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`ORDR_DTL_NO`, `ORDR_NO`, `ORDR_DTL_CD`, `ORDR_CD`) USING BTREE
)
COMMENT='주문-상품상세'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=63
;


CREATE TABLE `Z_BAK_ORDR_REBILL_231114` (
	`REBILL_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '번호',
	`ORDR_NO` INT(11) NULL DEFAULT NULL COMMENT '주문번호',
	`ORDR_CD` VARCHAR(100) NULL DEFAULT NULL COMMENT '주문코드' COLLATE 'utf8mb4_unicode_ci',
	`ORDR_CNT` INT(11) NULL DEFAULT NULL COMMENT '주문수',
	`STLM_AMT` INT(11) NULL DEFAULT NULL COMMENT '결제_금액',
	`STLM_YN` CHAR(1) NULL DEFAULT NULL COMMENT '결제_여부' COLLATE 'utf8mb4_unicode_ci',
	`STLM_DT` DATETIME NULL DEFAULT NULL COMMENT '결제_일시',
	`DELNG_NO` VARCHAR(100) NULL DEFAULT NULL COMMENT '승인_번호' COLLATE 'utf8mb4_unicode_ci',
	`CARD_CO_NM` VARCHAR(100) NULL DEFAULT NULL COMMENT '카드회사명' COLLATE 'utf8mb4_unicode_ci',
	`CARD_NO` VARCHAR(100) NULL DEFAULT NULL COMMENT '카드번호' COLLATE 'utf8mb4_unicode_ci',
	`CARD_APRVNO` VARCHAR(255) NULL DEFAULT NULL COMMENT '카드_승인번호' COLLATE 'utf8mb4_unicode_ci',
	`MEMO` VARCHAR(255) NULL DEFAULT NULL COMMENT '메모' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`REBILL_NO`) USING BTREE
)
COMMENT='주문_정기결제'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
*/