-- 매칭앱에서 로그인을 지속할 컬럼
ALTER TABLE MBR ADD APP_MAT_TOKEN VARCHAR(1024) NULL DEFAULT NULL COMMENT '매칭앱 로그인 토큰';
ALTER TABLE MBR ADD APP_MAT_EXPIRED_DT DATETIME NULL DEFAULT NULL COMMENT '매칭앱 토큰 만료일';
-- 매칭앱에서 로그인 시 수집되는 컬럼
ALTER TABLE MBR ADD LAT VARCHAR(128) NULL DEFAULT NULL COMMENT '위도';
ALTER TABLE MBR ADD LOT VARCHAR(128) NULL DEFAULT NULL COMMENT '경도';
