-- 회원 매칭앱 설정정보 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`MBR_APP_SETTING` (
    `APP_SETTING_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `MBR_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '회원_유니크_ID',
    `ALLOW_PUSH_YN` CHAR(1) NULL DEFAULT NULL COMMENT '알림 메시지 권한 허용',
    `ALLOW_PUSH_DT` DATETIME NULL DEFAULT NULL COMMENT '알림 메시지 권한 설정일',
    `ALLOW_LOCATION_YN` CHAR(1) NULL DEFAULT NULL COMMENT '위치 권한 허용',
    `ALLOW_LOCATION_DT` DATETIME NULL DEFAULT NULL COMMENT '위치 권한 설정일',
    `ALLOW_TEL_YN` CHAR(1) NULL DEFAULT NULL COMMENT '전화 걸기 권한 허용',
    `ALLOW_TEL_DT` DATETIME NULL DEFAULT NULL COMMENT '전화 걸기 권한 설정일',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    `MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시',
    PRIMARY KEY (`APP_SETTING_NO`)
)
COMMENT='회원 매칭앱 설정정보 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;