-- 회원 CI 키 컬럼 추가
ALTER TABLE MBR ADD CI_KEY VARCHAR(255) NULL DEFAULT NULL COMMENT '본인 인증 CI 값' AFTER DADDR;
-- 회원 로그인 타입 컬럼 추가
ALTER TABLE MBR ADD LGN_TY CHAR(1) NULL DEFAULT NULL COMMENT '로그인 시 인증 타입' AFTER JOIN_DT;

-- 회원 인증수단 정보 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`MBR_AUTH` (
    `AUTH_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `MBR_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '회원_유니크_ID',
    `JOIN_TY` CHAR(1) NULL DEFAULT NULL COMMENT '인증 구분',
    `MBR_ID` VARCHAR(100) NULL DEFAULT NULL COMMENT '회원_아이디',
    `PSWD` VARCHAR(255) NULL DEFAULT NULL COMMENT '비밀번호',
    `NAVER_APP_ID` VARCHAR(255) NULL DEFAULT NULL COMMENT '네이버_앱_아이디',
    `KAKAO_APP_ID` VARCHAR(255) NULL DEFAULT NULL COMMENT '카카오_앱_아이디',
    `EML` VARCHAR(255) NULL DEFAULT NULL COMMENT '이메일',
    `MBL_TELNO` VARCHAR(15) NULL DEFAULT NULL COMMENT '휴대전화번호',
    `CI_KEY` VARCHAR(255) NULL DEFAULT NULL COMMENT 'CI',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    `DEL_DT` DATETIME NULL DEFAULT NULL COMMENT '삭제_일시',
    `DEL_YN` CHAR(1) NULL DEFAULT NULL COMMENT '삭제_여부',
    PRIMARY KEY (`AUTH_NO`)
)
COMMENT='회원 인증수단 정보 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;

-- 회원 인증 테이블에 SNS 토큰 컬럼 추가
ALTER TABLE MBR_AUTH ADD ACCESS_TOKEN VARCHAR(1024) NULL DEFAULT NULL COMMENT '엑세스_토큰';
ALTER TABLE MBR_AUTH ADD REFRESH_TOKEN VARCHAR(1024) NULL DEFAULT NULL COMMENT '리프레시_토큰';

-- 회원 -> 회원 인증 테이블 마이그레이션
INSERT INTO MBR_AUTH
(
    MBR_UNIQUE_ID,
    JOIN_TY,
    MBR_ID,
    PSWD,
    NAVER_APP_ID,
    KAKAO_APP_ID,
    REG_DT,
    DEL_YN
)
SELECT
UNIQUE_ID,
JOIN_TY,
MBR_ID,
PSWD,
NAVER_APP_ID,
KAKAO_APP_ID,
JOIN_DT,
'N'
FROM MBR
WHERE WHDWL_YN != 'Y';

-- 간편회원의 회원 ID 정보 초기화
UPDATE MBR SET MBR_ID = '' WHERE JOIN_TY IN ('K', 'N');