-- APP 버전 정보 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`APP_VERSION` (
    `VERSION_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `APP_NM` VARCHAR(64) NULL DEFAULT NULL COMMENT '앱 이름',
    `VERSION` VARCHAR(64) NULL DEFAULT NULL COMMENT '버전',
    `FORCE_YN` CHAR(1) NULL DEFAULT NULL COMMENT '강제 업데이트 여부',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    PRIMARY KEY (`VERSION_NO`)
)
COMMENT='APP 버전 정보 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;


-- 최초 버전 등록
INSERT INTO APP_VERSION(APP_NM, VERSION, FORCE_YN, REG_DT) VALUES ('dolbom', '1.0.0', 'Y', now());