CREATE TABLE `MBR_SIMPLETEST` (
	`MBR_SIMPLETEST_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`UNIQUE_ID` VARCHAR(12) NOT NULL COMMENT '회원 UNIQUE ID' COLLATE 'utf8mb4_unicode_ci',
	`RECIPIENTS_NO` INT(11) NOT NULL COMMENT '등록된 수급자 FK 번호',
	`TEST_TY` VARCHAR(50) NOT NULL COMMENT 'simple, care 구분' COLLATE 'utf8mb4_unicode_ci',
	`AGE` INT(11) NOT NULL DEFAULT '0' COMMENT '만나이',
	`GRADE` INT(11) NOT NULL COMMENT '계산된 등급',
	`SCORE` INT(11) NOT NULL COMMENT '계산된 점수',
	`CARE_TIME` INT(11) NOT NULL COMMENT 'care일경우 선택된 시간',
	`SELECTED_VALUE` VARCHAR(1024) NOT NULL COMMENT '선택된 값들' COLLATE 'utf8mb4_unicode_ci',
	`REG_DT` DATETIME NOT NULL DEFAULT current_timestamp(),
	`MDFCN_DT` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`MBR_SIMPLETEST_NO`) USING BTREE,
	INDEX `UNIQUE_ID` (`UNIQUE_ID`) USING BTREE,
	INDEX `RECIPIENTS_NO` (`RECIPIENTS_NO`)
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
