-- BPLC 회원 탈퇴 컬럼 추가
ALTER TABLE BPLC ADD LEAVE_CONFIRM_DATE VARCHAR(8) NULL DEFAULT NULL COMMENT '탈퇴일';
ALTER TABLE BPLC ADD LEAVE_REQUEST_DATE VARCHAR(20) NULL DEFAULT NULL COMMENT '탈퇴 신청일';
ALTER TABLE BPLC ADD LEAVE_REJECT_DATE VARCHAR(20) NULL DEFAULT NULL COMMENT '탈퇴 거부일';
ALTER TABLE BPLC ADD LEAVE_RESN TEXT NULL DEFAULT NULL COMMENT '탈퇴 사유';
ALTER TABLE BPLC ADD LEAVE_REJECT_RESN TEXT NULL DEFAULT NULL COMMENT '탈퇴 거부 사유';
ALTER TABLE BPLC ADD LEAVE_CONFIRM_NM VARCHAR(50) NULL DEFAULT NULL COMMENT '탈퇴 승인자';