-- 회원 매칭앱 설정정보 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`MBR_APP_SETTING` (
    `APP_SETTING_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `MBR_UNIQUE_ID` VARCHAR(12) NULL DEFAULT NULL COMMENT '회원_유니크_ID',
    `PUSH_TOKEN` VARCHAR(1024) NULL DEFAULT NULL COMMENT '알림 푸시 토큰',
    `ALLOW_PUSH_YN` CHAR(1) NULL DEFAULT NULL COMMENT '알림 메시지 권한 허용',
    `ALLOW_PUSH_DT` DATETIME NULL DEFAULT NULL COMMENT '알림 메시지 권한 설정일',
    `ALLOW_LOCATION_YN` CHAR(1) NULL DEFAULT NULL COMMENT '위치 권한 허용',
    `ALLOW_LOCATION_DT` DATETIME NULL DEFAULT NULL COMMENT '위치 권한 설정일',
    `ALLOW_TEL_YN` CHAR(1) NULL DEFAULT NULL COMMENT '전화 걸기 권한 허용',
    `ALLOW_TEL_DT` DATETIME NULL DEFAULT NULL COMMENT '전화 걸기 권한 설정일',
    `AUTO_LGN_YN` CHAR(1) NULL DEFAULT NULL COMMENT '자동로그인 여부',
    `AUTO_LGN_DT` DATETIME NULL DEFAULT NULL COMMENT '자동로그인 여부 선택일',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    `MDFCN_DT` DATETIME NULL DEFAULT NULL COMMENT '수정_일시',
    PRIMARY KEY (`APP_SETTING_NO`)
)
COMMENT='회원 매칭앱 설정정보 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;


-- 회원 동의항목 추가
ALTER TABLE MBR_AGREEMENT ADD MARKETING_RECEPTION_YN CHAR(1) NULL DEFAULT NULL COMMENT '이벤트 및 마켓팅 정보 수신 동의 여부';
ALTER TABLE MBR_AGREEMENT ADD MARKETING_RECEPTION_DT DATETIME NULL DEFAULT NULL COMMENT '이벤트 및 마켓팅 정보 수신 동의 선택시간';
ALTER TABLE MBR_AGREEMENT ADD NIGHT_RECEPTION_YN CHAR(1) NULL DEFAULT NULL COMMENT '야간 혜택 수신 동의 여부';
ALTER TABLE MBR_AGREEMENT ADD NIGHT_RECEPTION_DT DATETIME NULL DEFAULT NULL COMMENT '야간 혜택 수신 동의 선택시간';


-- 앱 디버그 로그 테이블
CREATE TABLE IF NOT EXISTS `eroumcare`.`APP_LOG` (
    `APP_LOG_NO` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `LOG` TEXT NULL DEFAULT NULL COMMENT '로그',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록_일시',
    PRIMARY KEY (`APP_LOG_NO`)
)
COMMENT='앱 디버그 로그 테이블'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;